In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
from sklearn import metrics


In [23]:
puppy = pd.read_csv("logtest.csv")

In [24]:
puppy["DescriptionLenght"] = puppy["DescriptionLenght"].fillna(0)

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(puppy.drop("AdoptionSpeed",axis=1),puppy['AdoptionSpeed'],
                                                    test_size=0.30)

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
lmodel = linear_model.LogisticRegression()

In [28]:
mul_lr = linear_model.LogisticRegression(multi_class='multinomial', solver='saga',max_iter=1000)

In [29]:
mul_lr.fit(X_train, y_train)
lmodel.fit(X_train, y_train)

prediction = lmodel.predict(X_train)
predictionsmul = mul_lr.predict(X_test)

C:\Users\raian\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
C:\Users\raian\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\raian\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [30]:
print "Logistic regression Train Accuracy :: ", metrics.accuracy_score(y_train, lr.predict(X_train))
print "Logistic regression Test Accuracy :: ", metrics.accuracy_score(y_test, prediction)
    
print "Multinomial Logistic regression Train Accuracy :: ", metrics.accuracy_score(y_train, mul_lr.predict(X_train))
print "Multinomial Logistic regression Test Accuracy :: ", metrics.accuracy_score(y_test, predictionmul)

SyntaxError: invalid syntax (<ipython-input-30-08eb8dc750bf>, line 1)

In [ ]:
print "Multinomial Logistic regression Train Accuracy :: ", metrics.accuracy_score((y_train, mul_lr.predict(X_train))
print "Multinomial Logistic regression Test Accuracy :: ", metrics.accuracy_score((y_test,predictionmul)

In [31]:
from sklearn.metrics import classification_report

print(classification_report(y_test,predictionsmul))

              precision    recall  f1-score   support

           0       0.48      0.95      0.64      3403
           1       0.00      0.00      0.00      1515
           2       0.39      0.07      0.12      2171

    accuracy                           0.48      7089
   macro avg       0.29      0.34      0.25      7089
weighted avg       0.35      0.48      0.34      7089



C:\Users\raian\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [32]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test,predictionsmul))

[[3249    0  154]
 [1436    0   79]
 [2020    0  151]]
